### PR TITLE
Add Chapter 2.A rules to "all the rules we know"

### PR DESCRIPTION
**Pull request by llewelld**
Adds the rules from Chapter 2.A of Axler to the "all the rules we know" document.

### CODE REVIEW

**Comment by llewelld** [comment]
I won't merge until after the session tomorrow, but was hoping to queue it up ready.

**Comment by llewelld** [comment]
Preview: [all-the-rules-we-know.pdf](https://github.com/llewelld/hut23-linear-algebra/blob/gh-action-result/pdf-files/reference/all-the-rules-we-know.pdf)

**Review by triangle-man — APPROVED** [review]
Looks good to me.

**Comment by llewelld** [comment]
Thanks for checking it!

**Pull request merged**
