### PR TITLE
Add Chapter 3.B rules to "all the rules we know"

### PR DESCRIPTION
**Pull request by llewelld**

### CODE REVIEW

**Comment by llewelld** [comment]
Preview with these changes:
https://github.com/llewelld/hut23-linear-algebra/blob/gh-action-result/pdf-files/reference/all-the-rules-we-know.pdf

**Comment by llewelld** [comment]
@rwood-97: if reviewing these is getting too cumbersome, please say (but I do really appreciate it).

**Comment by llewelld** [comment]
Rebased.

**Review by rwood-97 — APPROVED** [review]
🚀

**Comment by llewelld** [comment]
Thank you @rwood-97!

Rebased before merging.

**Pull request merged**
