### PR TITLE
Add Chapter 4 and 5.A rules to "all the rules we know"

### PR DESCRIPTION
**Pull request by llewelld**
Updates the rules document to cover Chapters 4 and 5.A.

### CODE REVIEW

**Comment by llewelld** [comment]
Prebuilt preview: https://github.com/llewelld/hut23-linear-algebra/blob/gh-action-result/pdf-files/reference/all-the-rules-we-know.pdf

**Comment by llewelld** [comment]
Rebased.

**Comment by rwood-97** [comment]
5A looks good, maybe chapter 4 should be an appendix or similar since we skipped it so maybe don't "know" these rules

**Comment by llewelld** [comment]
> 5A looks good, maybe chapter 4 should be an appendix or similar since we skipped it so maybe don't "know" these rules

I thought about this, but unfortunately some of the later results and exercises rely on results from 4, so I'm a bit reticent about "hiding" it. Would you mind if it were kept in the main flow?

**Review by rwood-97 — APPROVED** [review]

**Comment by rwood-97** [comment]
Okay yes I think this makes sense to keep it since we have used these definitions quite a lot

**Comment by llewelld** [comment]
Thanks, as always, for your review @rwood-97.

**Pull request merged**
