### PR TITLE
Add Chapter 2.B and 2.C rules to "all the rules we know"

### PR DESCRIPTION
**Pull request by llewelld**
In preparation for the next sections; I'll hold off merging until after the session tomorrow.

### CODE REVIEW

**Comment by llewelld** [comment]
PDF preview of the changes: https://github.com/llewelld/hut23-linear-algebra/blob/gh-action-result/pdf-files/reference/all-the-rules-we-know.pdf

**Comment by llewelld** [comment]
If you could put my mind at rest and take a look at this @rwood-97 I'd be really grateful!

**Review by rwood-97 — APPROVED** [review]

**Comment by llewelld** [comment]
Thank you @rwood-97!

**Comment by llewelld** [comment]
Rebased.

**Pull request merged**
