### PR TITLE
Add Chapter 3.A rules to "all the rules we know"

### PR DESCRIPTION
**Pull request by llewelld**
Builds on #15, #17 and #19; so those should be merged in first (the diff here will be much clearer once they have been).

### CODE REVIEW

**Comment by llewelld** [comment]
I know @triangle-man was happy for me to just merge these straight in, but it does rather go against the grain, plus I'd appreciate any review comments. So if anyone has the chance to review this I'd be grateful (or failing that, just an approval so I don't feel so bad!).

**Comment by llewelld** [comment]
Link to pre-build PDF preview output: https://github.com/llewelld/hut23-linear-algebra/blob/gh-action-result/pdf-files/reference/all-the-rules-we-know.pdf

**Comment by llewelld** [comment]
Rebased.

**Review by rwood-97 — APPROVED** [review]

**Comment by llewelld** [comment]
Thanks for reviewing this @rwood-97 (somehow I missed the fact earlier).

**Comment by llewelld** [comment]
Rebased.

**Pull request merged**
